сделал Fighters
tanyginvv/travelline_practice pull request #1
Opened 2024-03-22 11:19 UTC by tanyginvv

2024-03-28 17:14 UTC, VimperSky requested changes

2024-04-01 15:43 UTC, VladStrTL commented
test

2024-04-01 18:26 UTC, VladTL commented
В целом мне особо больше не к чему придраться, я аппрувну, а мелочи поправь.

Я удалил несколько своих старых комментов (случайно написал их не с того аккаунта), там было все ок. Но вообще комменты/PR/Issues и все остальное лучше не удалять, все пригодится для истории.

2024-04-01 18:26 UTC, VladTL approved these changes

2024-04-01 18:26 UTC, VladTL commented on Fighters/Fighters/GameMaster.cs
> +                    FightAndCheckIfOpponentDead(attacker, defender);
Метод возвращает bool и проверяет что OpponentDead, а результат не используешь, ниже по сути та же самая проверка используется. Либо используй результат метода, либо оставь нижнюю проверку.

2024-04-01 18:26 UTC, VladTL commented on Fighters/Fighters/FighterFactory.cs
> +    public class FighterFactory
можно статиком сделать

2024-04-01 19:21 UTC, merged