Car factory
tanyginvv/travelline_practice pull request #3
Opened 2024-03-22 20:15 UTC by tanyginvv

2024-04-02 13:57 UTC, Nafanyan commented
Дружище, у тебя лишние изменения в коммит попали)))

2024-04-02 19:04 UTC, Nafanyan requested changes
В целом хорошо, но можно лучше)))

Будут вопросы, пиши @nafanyann

И было бы неплохо убрать ненужные изменения с этого ПРа, всё таки он относится к CarFactory)

2024-04-02 19:04 UTC, Nafanyan commented on Fighters/CarFactory/Car.cs
> +        private IBrand Brand { get; set; }
зачем тебе приватные Property? А если я захочу узнать только марку у данной машины?

попробуй сделать само Property публичным, а set приватным

2024-04-02 19:04 UTC, Nafanyan commented on Fighters/CarFactory/Car.cs
> +        private int MaxSpeed  => Engine.MaxSpeed + Tramsmission.MaxSpeed;
Если это поле (не Property) то с маленькой буквы и с нижним подчеркиванием)

2024-04-03 19:21 UTC, Nafanyan requested changes
И ещё перемести вторую домашку в директорию homework2

2024-04-03 19:21 UTC, Nafanyan commented on Fighters/CarFactory/CarBuilder.cs
> +            int brandChoice = int.Parse(Console.ReadLine() ?? throw new Exception("Invalid brand"));
Если создаёшь Exception, то его нужно обрабатыват, иначе прога поломается

2024-04-03 19:21 UTC, Nafanyan commented on Fighters/CarFactory/Factories/ModelFactory.cs
> +                    return ["Camry", "Supra"];
Можно так, а можно более явно)
new List<string> { "Camry", "Supra" }

В других случаях аналогично, но это вкусовщина

2024-04-03 19:21 UTC, Nafanyan commented on Fighters/CarFactory/Factories/BodyTypeFactory.cs
> +    public class BodyTypeFactory
У тебя все методы статические, логично было бы класс сделать тоже статическим, но статика это зло потому как в дальнейшем при написании тестов могут возникнуть проблемы с созданием заглушек. 

Статику лучше всего использовать по минимуму)

Аналогично с другими фабриками.

2024-04-03 19:21 UTC, Nafanyan commented on Fighters/CarFactory/Factories/BodyTypeFactory.cs
> +        }
Пустая строка между методами

Аналогично с другими фабриками.

2024-04-03 19:21 UTC, Nafanyan commented on Fighters/CarFactory/CarFactory.cs
> +        public static Car CreateCar(IBrand brand,
IBrand brand с новой строки

2024-04-06 18:40 UTC, tanyginvv commented on Fighters/CarFactory/Factories/BodyTypeFactory.cs
> +﻿using CarFactory.Models.BodyType;
закинул каждую фабрику в соответствующую папку модели

2024-04-09 06:29 UTC, Nafanyan requested changes

2024-04-09 06:29 UTC, Nafanyan commented on Fighters/CarFactory/Car.cs
> +    public class Car
Car, CarOptions и CarFactory лучше перенести в Models как это с другими критериями, по сути тажа самая модель)

2024-04-09 06:29 UTC, Nafanyan commented on Fighters/CarFactory/Program.cs
> +﻿
Пустые строки

2024-04-09 06:29 UTC, Nafanyan commented on Fighters/CarFactory/Models/BodyType/BodyTypeFactory.cs
> +            Console.WriteLine("Доступные типы кузова:");
nid: Можно так, а можно одним вызовом Console.WriteLine используя оператор перехода на новую строку \n)

А ещё думаю лучше здесь возвращать string, чтобы дать возможность интерпретировать отображение этой строки по разному, в UI консоли или графической формы, ну и метод тогда будет называться по другому. Аналогично с другими фабриками.

2024-04-09 06:29 UTC, Nafanyan commented on Fighters/CarFactory/CarFactory.cs
> +        IBrand brand,
Нужен отступ
![image](https://github.com/tanyginvv/travelline_practice/assets/90004716/94385df9-20a9-4f1a-bf32-497eaa5ea213)

2024-04-09 21:25 UTC, merged